api_platform:
  title: Hello API Platform
  version: 1.0.0
  formats:
    json: ["application/json"] # format par défaut de retour des ressources API
    jsonld: ["application/ld+json"] #format pour les tests
  patch_formats:
    json: ["application/merge-patch+json"] # format de données lors du patch d'une ressource
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
